// frontend-angular/src/app/features/onboarding/components/register-customer-form/register-customer-form.ts
import { CreateCustomerRequest } from './../../../../dtos/customers/requests/create-customer-request';
import { Component, ChangeDetectionStrategy, signal, inject } from '@angular/core';
import { FormSection } from '../../../../shared/components/forms/form-section/form-section';
import { FormField } from '../../../../shared/components/forms/form-field/form-field';
import { Input } from '../../../../shared/components/inputs/input/input';
import { Button } from '../../../../shared/components/button/button';
import { email, form, minLength, required, FormField as NgFormField, FormRoot, validate } from '@angular/forms/signals';
import { firstValueFrom } from 'rxjs';
import { CustomerService } from '../../../../api/services/customers/customer-service';

interface RegisterCustomerModel {
  email: string;
  password: string;
  confirmPassword: string;

  firstName: string;
  lastName: string;
  phone: string;

  street: string;
  district: string;
  number: string;
  complement: string;
  reference: string;
  zipCode: string;
  city: string;
  state: string;
  country: string;
}

@Component({
  selector: 'app-register-customer-form',
  imports: [FormSection, FormField, Input, Button, NgFormField, FormRoot],
  templateUrl: './register-customer-form.html',
  changeDetection: ChangeDetectionStrategy.Eager,
  styleUrl: './register-customer-form.css',
})
export class RegisterCustomerForm {

  private customerService = inject(CustomerService);

  protected model = signal<RegisterCustomerModel>({
    email: '',
    password: '',
    confirmPassword: '',

    firstName: '',
    lastName: '',
    phone: '',

    street: '',
    district: '',
    number: '',
    complement: '',
    reference: '',
    zipCode: '',
    city: '',
    state: '',
    country: '',
  });

  protected form = form(this.model, (path) => {
    required(path.email, {
      message: 'Email is required'
    });
    email(path.email, {
      message: 'Please enter a valid email address'
    });

    required(path.password, {
      message: 'Password is required'
    });
    minLength(path.password, 8, {
      message: 'Password must be at least 8 characters long'
    });

    required(path.confirmPassword, {
      message: 'Please confirm your password'
    });
    validate(path.confirmPassword, ({ value, valueOf }) => {
      if (!value()) {
        return null;
      }

      if (value() !== valueOf(path.password)) {
        return {
          kind: 'passwordMismatch',
          message: 'Passwords do not match.',
        };
      }

      return null;
    });

    required(path.firstName, {
      message: 'First name is required'
    });
    required(path.lastName, {
      message: 'Last name is required'
    });

    required(path.street, {
      message: 'Street is required'
    });
    required(path.district, {
      message: 'District is required'
    });

    required(path.zipCode, {
      message: 'Zip Code is required'
    });
    required(path.city, {
      message: 'City is required'
    });
    required(path.state, {
      message: 'State is required'
    });
    required(path.country, {
      message: 'Country is required'
    });
  },
  {
    submission: {
      action: async (field) => {
        const data = field().value()

        const createCustomerRequest: CreateCustomerRequest = {
          email: data.email,
          plainPassword: data.password,
          firstName: data.firstName,
          lastName: data.lastName,
          phone: data.phone,
          address: {
            street: data.street,
            district: data.district,
            number: data.number,
            complement: data.complement,
            reference: data.reference,
            zipCode: data.zipCode,
            city: data.city,
            state: data.state,
            country: data.country
          }
        };

        const customer = await firstValueFrom(
          this.customerService.createCustomer(createCustomerRequest)
        );

        console.log(customer);
      }
    }
  }
  );
}

// frontend/src/modules/customers/components/forms/RegisterCustomerForm.tsx
import { useForm } from "react-hook-form";
import FormSection from "../../../shared/generic/components/forms/FormSection";
import FormField from "../../../shared/generic/components/forms/FormField";
import Input from "../../../shared/generic/components/inputs/Input";
import Button from "../../../shared/generic/components/buttons/Button";
import { zodResolver } from "@hookform/resolvers/zod";
import { registerCustomerSchema, type RegisterCustomerForm } from "../../schema/registerCustomerSchema";
import { registerCustomer } from "../../api/customerService";


export default function RegisterCustomerForm(){

    const {register, handleSubmit, formState: { errors }} = useForm<RegisterCustomerForm>({
        resolver: zodResolver(registerCustomerSchema)
    });

    const onSubmit = async (data: RegisterCustomerForm) => {
        
        const { confirmPassword, ...request } = data;

        const costumerResponse = await registerCustomer(request);
        console.log(costumerResponse);
    };

    return (
        <form onSubmit={handleSubmit(onSubmit)} noValidate>
            <FormSection title="Account Information">
                <FormField
                    label="Email"
                    className="md:col-span-2"
                    required
                    error={errors.email?.message}
                >
                    <Input
                        type="email"
                        placeholder="john@email.com"
                        {...register("email")}
                    />
                </FormField>

                <FormField
                    label="Password"
                    className="md:col-span-2"
                    required 
                    error={errors.plainPassword?.message}             
                >
                    <Input 
                        type="password"
                        {...register("plainPassword")}
                    />
                </FormField>

                <FormField
                    label="Confirm Password"
                    className="md:col-span-2"
                    required
                    error={errors.confirmPassword?.message}
                >
                    <Input 
                        type="password"
                        {...register("confirmPassword")}
                    />  
                </FormField>
            </FormSection>

            <FormSection title="Personal Information">
                <FormField label="First Name" required error={errors.firstName?.message}>
                    <Input placeholder="John" {...register("firstName")}/>
                </FormField>

                <FormField
                    label="Last Name"
                    required
                    error={errors.lastName?.message}
                >
                    <Input
                        placeholder="Doe"
                        {...register("lastName")}
                    />
                </FormField>
        
                <FormField
                    label="Phone Number"       
                    error={errors.phoneNumber?.message}      
                >
                    <Input 
                        {...register("phoneNumber")}
                    />
                </FormField>
            </FormSection>

            <FormSection title="Address">
                <FormField
                    label="Street"
                    required
                    error={errors.address?.street?.message}
                >
                    <Input 
                        placeholder="Rua Alberto Silva"
                        {...register("address.street")}
                    />
                </FormField>
                <FormField
                    label="District"
                    required
                    error={errors.address?.district?.message}
                >
                    <Input 
                        placeholder="Centro"
                        {...register("address.district")}
                    />
                </FormField>
                <FormField
                    label="Number"
                    error={errors.address?.number?.message}
                >
                    <Input placeholder="45" {...register("address.number")} />
                </FormField>
                <FormField
                    label="Complement"
                    error={errors.address?.complement?.message}
                >
                    <Input {...register("address.complement")}/>
                </FormField>
                <FormField
                    label="Reference"
                    error={errors.address?.reference?.message}
                >
                    <Input placeholder="perto da praça" {...register("address.reference")}/>
                </FormField>
                <FormField
                    label="Zip Code"
                    required
                    error={errors.address?.zipCode?.message}
                >
                    <Input placeholder="00000-000" {...register("address.zipCode")}/>
                </FormField>
                <FormField
                    label="City"
                    required
                    error={errors.address?.city?.message}
                >
                    <Input {...register("address.city")} />
                </FormField>
                <FormField
                    label="State"
                    required
                    error={errors.address?.state?.message}
                >
                    <Input {...register("address.state")} />
                </FormField>
                <FormField
                    label="Country"
                    required
                    error={errors.address?.country?.message}
                >
                    <Input {...register("address.country")} />
                </FormField>
            </FormSection>

            <div className="mt-6">
                <Button type="submit">
                    Register
                </Button>
            </div>       
        </form>     
    );
}
