// frontend-angular/src/app/features/onboarding/components/register-seller-form/register-seller-form.ts
import { email, form, FormRoot, minLength, required, validate, FormField as formField } from '@angular/forms/signals';
import { Component, ChangeDetectionStrategy, signal, inject } from '@angular/core';
import { FormSection } from '../../../../shared/components/forms/form-section/form-section';
import { FormField } from '../../../../shared/components/forms/form-field/form-field';
import { Input } from '../../../../shared/components/inputs/input/input';
import { Button } from '../../../../shared/components/button/button';
import { Textarea } from '../../../../shared/components/inputs/textarea/textarea';
import { SellerService } from '../../../../api/services/sellers/seller-service';
import { CreateSellerRequest } from '../../../../dtos/sellers/requests/create-seller-request';
import { firstValueFrom } from 'rxjs';

interface RegisterSellerModel {
  name: string;
  email: string;
  password: string;
  confirmPassword: string;
  about: string;
}

@Component({
  selector: 'app-register-seller-form',
  imports: [FormSection, FormField, FormRoot, Input, Button, Textarea, formField],
  templateUrl: './register-seller-form.html',
  changeDetection: ChangeDetectionStrategy.Eager,
  styleUrl: './register-seller-form.css',
})
export class RegisterSellerForm {

  private sellerService = inject(SellerService);

  protected model = signal<RegisterSellerModel>(
    {
      name: '',
      email: '',
      password: '',
      confirmPassword: '',
      about: ''
    }
  );

  protected form = form(this.model, (path) => {

    required(path.name, {
      message: 'Name is required'
    });

    required(path.email, {
      message: 'Email is required'
    });
    email(path.email, {
      message: 'Please enter a valid email address'
    });

    required(path.password, {
      message: 'Password is required'
    });
    minLength(path.password, 8, {
      message: 'Password must be at least 8 characters long'
    });

    required(path.confirmPassword, {
      message: 'Please confirm your password'
    });
    validate(path.confirmPassword, ({ value, valueOf }) => {
      if (!value()) {
        return null;
      }

      if (value() !== valueOf(path.password)) {
        return {
          kind: 'passwordMismatch',
          message: 'Passwords do not match.',
        };
      }

      return null;
    });
  },
  {
    submission: {
      action: async (field) => {
        const data = field().value();
        console.log(data);
        const createSellerRequest : CreateSellerRequest = {
          email: data.email,
          name: data.name,
          plainPassword: data.password,
          about: data.about
        };

        const seller = await firstValueFrom(
          this.sellerService.createSeller(createSellerRequest)
        );

        console.log(seller);
      }
    }
  }
  );
}

// frontend/src/modules/sellers/components/forms/RegisterSellerForm.tsx
import { zodResolver } from "@hookform/resolvers/zod";
import FormField from "../../../shared/generic/components/forms/FormField";
import FormSection from "../../../shared/generic/components/forms/FormSection";
import Input from "../../../shared/generic/components/inputs/Input";
import { registerSellerSchema, type RegisterSellerForm } from "../../schema/registerSellerSchema";
import { useForm } from "react-hook-form";
import Button from "../../../shared/generic/components/buttons/Button";
import Textarea from "../../../shared/generic/components/inputs/Textarea";
import { registerSeller } from "../../api/sellerService";

export default function RegisterSellerForm(){

    const {register, handleSubmit, formState: { errors }} = useForm<RegisterSellerForm>({
        resolver: zodResolver(registerSellerSchema)
    });

    const onSubmit = async (data: RegisterSellerForm) => {
        
        const { confirmPassword, ...request } = data;

        const sellerResponse = await registerSeller(request);
        console.log(sellerResponse);
    };

    return (
        <form onSubmit={handleSubmit(onSubmit)} noValidate>
            <FormSection title="Account Information">
                <FormField
                        label="Name"
                        className="md:col-span-2"
                        required
                        error={errors.name?.message}
                    >
                        <Input
                            placeholder="seller name"
                            {...register("name")}
                        />
                </FormField>

                <FormField
                    label="Email"
                    className="md:col-span-2"
                    required
                    error={errors.email?.message}
                >
                    <Input
                        type="email"
                        placeholder="john@email.com"
                        {...register("email")}
                    />
                </FormField>

                <FormField
                    label="Password"
                    className="md:col-span-2"
                    required 
                    error={errors.plainPassword?.message}             
                >
                    <Input 
                        type="password"
                        {...register("plainPassword")}
                    />
                </FormField>

                <FormField
                    label="Confirm Password"
                    className="md:col-span-2"
                    required
                    error={errors.confirmPassword?.message}
                >
                    <Input 
                        type="password"
                        {...register("confirmPassword")}
                    />  
                </FormField>

                <FormField
                    label="About"
                    className="md:col-span-2"
                >
                    <Textarea
                        name="about"
                        placeholder="Tell us about yourself"
                        className="h-32"
                        {...register("about")}
                    />
                </FormField>     
            </FormSection>   

            <div className="mt-6">
                <Button type="submit">
                    Register
                </Button>
            </div>       
        </form>
    );
}
